#!/usr/bin/env python
#
# (c)oded 2015, Marek Chalupa
# E-mail: statica@fi.muni.cz
#
# Permission to use, copy, modify, distribute, and sell this software and its
# documentation for any purpose is hereby granted without fee, provided that
# the above copyright notice appear in all copies and that both that copyright
# notice and this permission notice appear in supporting documentation, and
# that the name of the copyright holders not be used in advertising or
# publicity pertaining to distribution of the software without specific,
# written prior permission. The copyright holders make no representations
# about the suitability of this software for any purpose. It is provided "as
# is" without express or implied warranty.
#
# THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
# EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY SPECIAL, INDIRECT OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
# DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
# On arran we have only python2, so use python2

import os
import sys
from database import get_db_credentials, check_db_credentials, DatabaseConnection

def print_help():
    print('When given query as the only argument on command line,\n'
          'it will be processed and the tool will exit.')
    print('\nInteractively you can use these commands:')
    print('\tmysql\t\tLog into interactive mysql')

def get_input(prompt = '> '):
    try:
        s = str(raw_input(prompt))
        return s.strip()
    except EOFError:
        return None
    except KeyboardInterrupt:
        return None

if __name__ == "__main__":
    argc = len(sys.argv)

    if argc > 2:
        sys.stderr.write('0 or 1 argument excepted (mysql query)\n')
        sys.exit(1)

    db = DatabaseConnection()

    # if we got query given on command line, process it and exit
    if argc == 2:
        res = db.query(sys.argv[1])
        for r in res:
            print(r)

        db.commit() # commit result if it was modification
        sys.exit(0)

    line = get_input()
    while not line is None:
        if line == 'mysql':
            host, user, passwd, db = get_db_credentials()
            check_db_credentials(host, user, passwd, db)

            cmd = 'mysql --user={0} --password={1} --host={2} {3}'.format(user, passwd, host, db)
            os.system(cmd)
        elif line == 'help':
            print_help()
        else:
            if line != '':
                print('Unknown command')

        line = get_input()

    print('') # print last newline
